import type { FastifyInstance } from "fastify";
import type { Prisma } from "@prisma/client";
import { Queue } from "bullmq";
import { redisConnection } from "../../config/redis.js";
import { uploadFile } from "../../lib/s3.js";
import type { CreateAppointmentInput, UpdateAppointmentInput, FinalizeAppointmentInput } from "./appointments.schema.js";

const documentQueue = new Queue("document-generation", { connection: redisConnection });

async function uploadClientSignature(
  tenantId: string,
  appointmentId: string,
  dataUrl: string
): Promise<string> {
  const match = dataUrl.match(/^data:image\/(png|jpeg);base64,(.+)$/);
  if (!match) throw new Error("Invalid signature data URL");
  const buffer = Buffer.from(match[2], "base64");
  const ext = match[1];
  const s3Key = `${tenantId}/signatures/client/${appointmentId}.${ext}`;
  await uploadFile(s3Key, buffer, `image/${ext}`);
  return s3Key;
}

async function generateAndSendGdpr(
  fastify: FastifyInstance,
  tenantId: string,
  clientId: string,
  clientSignatureS3Key: string | null
) {
  const templates = await fastify.prisma.documentTemplate.findMany({
    where: {
      categoryCode: "GDPR",
      OR: [{ tenantId }, { tenantId: null }],
      isActive: true,
    },
  });
  if (templates.length === 0) return;

  for (const template of templates) {
    const document = await fastify.prisma.document.create({
      data: {
        tenantId,
        templateId: template.id,
        name: `Acord GDPR - auto`,
        status: "PENDING",
        clients: { create: { clientId } },
        contextJson: clientSignatureS3Key
          ? ({ clientSignatureS3Key, gdprAutoGenerated: true } as Prisma.InputJsonValue)
          : ({ gdprAutoGenerated: true } as Prisma.InputJsonValue),
      },
    });
    await documentQueue.add("generate", {
      documentId: document.id,
      tenantId,
      clientId,
      templateId: template.id,
    });
  }
}

async function regenerateIscirDocument(
  fastify: FastifyInstance,
  tenantId: string,
  _appointmentId: string,
  revisionId: string,
  sendToEmail?: string
) {
  // Find the revision and its equipment/client
  const revision = await fastify.prisma.equipmentRevision.findUnique({
    where: { id: revisionId },
    include: { equipment: { include: { client: true } } },
  });
  if (!revision) return;
  const clientId = revision.equipment.clientId;

  const iscirTemplate = await fastify.prisma.documentTemplate.findFirst({
    where: {
      categoryCode: "REVIZIE_CENTRALA",
      OR: [{ tenantId }, { tenantId: null }],
      isActive: true,
    },
  });
  if (!iscirTemplate) return;

  // Reuse existing document if one is already linked to this revision
  let documentId = revision.iscirDocumentId;

  const ctxJson = sendToEmail ? ({ sendToEmail } as Prisma.InputJsonValue) : undefined;

  if (documentId) {
    await fastify.prisma.document.update({
      where: { id: documentId },
      data: {
        status: "PENDING",
        s3Key: null,
        errorMessage: null,
        ...(ctxJson && { contextJson: ctxJson }),
      },
    });
  } else {
    const document = await fastify.prisma.document.create({
      data: {
        tenantId,
        templateId: iscirTemplate.id,
        name: `Revizie ${revision.equipment.name ?? ""} - ${new Date().toLocaleDateString("ro-RO")}`.trim(),
        status: "PENDING",
        clients: { create: { clientId } },
        contextJson: ctxJson,
      },
    });
    documentId = document.id;
    await fastify.prisma.equipmentRevision.update({
      where: { id: revision.id },
      data: { iscirDocumentId: documentId },
    });
  }

  await documentQueue.add("generate", {
    documentId,
    tenantId,
    clientId,
    templateId: iscirTemplate.id,
    revisionId: revision.id,
  });
}

const listInclude = {
  project: { select: { id: true, name: true, status: true } },
  client: { select: { id: true, companyName: true, firstName: true, lastName: true, phone: true, email: true, addresses: { select: { address: true, isPrimary: true, city: { select: { name: true } }, state: { select: { name: true } } }, orderBy: { isPrimary: "desc" as const } } } },
  employee: { select: { id: true, firstName: true, lastName: true } },
} as const;

export async function listByProject(
  fastify: FastifyInstance,
  tenantId: string,
  projectId?: string
) {
  return fastify.prisma.appointment.findMany({
    where: { tenantId, deletedAt: null, ...(projectId && { projectId }) },
    include: listInclude,
    orderBy: { date: "asc" },
  });
}

export async function calendar(
  fastify: FastifyInstance,
  tenantId: string,
  from: Date,
  to: Date
) {
  return fastify.prisma.appointment.findMany({
    where: {
      tenantId,
      deletedAt: null,
      date: { gte: from, lte: to },
      status: { not: "cancelled" },
    },
    include: {
      project: {
        select: {
          id: true,
          name: true,
          status: true,
          client: { select: { id: true, companyName: true, firstName: true, lastName: true } },
          projectType: { select: { id: true, name: true, code: true } },
        },
      },
      client: { select: { id: true, companyName: true, firstName: true, lastName: true, phone: true, email: true, addresses: { select: { address: true, isPrimary: true, city: { select: { name: true } }, state: { select: { name: true } } }, orderBy: { isPrimary: "desc" as const } } } },
      employee: { select: { id: true, firstName: true, lastName: true } },
    },
    orderBy: { date: "asc" },
  });
}

export async function create(
  fastify: FastifyInstance,
  tenantId: string,
  input: CreateAppointmentInput
) {
  // Verify project belongs to tenant (if provided)
  if (input.projectId) {
    const project = await fastify.prisma.project.findFirst({
      where: { id: input.projectId, tenantId },
    });
    if (!project) throw fastify.httpErrors.notFound("Project not found");
  }

  return fastify.prisma.appointment.create({
    data: {
      tenantId,
      projectId: input.projectId ?? null,
      clientId: input.clientId ?? null,
      employeeId: input.employeeId,
      type: input.type,
      title: input.title,
      notes: input.notes,
      date: new Date(input.date),
      duration: input.duration,
    },
    include: listInclude,
  });
}

export async function update(
  fastify: FastifyInstance,
  tenantId: string,
  id: string,
  input: UpdateAppointmentInput
) {
  const appointment = await fastify.prisma.appointment.findFirst({
    where: { id, tenantId, deletedAt: null },
  });
  if (!appointment) throw fastify.httpErrors.notFound("Appointment not found");

  return fastify.prisma.appointment.update({
    where: { id },
    data: {
      ...(input.title !== undefined && { title: input.title }),
      ...(input.notes !== undefined && { notes: input.notes }),
      ...(input.date !== undefined && { date: new Date(input.date) }),
      ...(input.duration !== undefined && { duration: input.duration }),
      ...(input.employeeId !== undefined && { employeeId: input.employeeId }),
      ...(input.status !== undefined && { status: input.status }),
    },
    include: listInclude,
  });
}

export async function finalize(
  fastify: FastifyInstance,
  tenantId: string,
  id: string,
  input: FinalizeAppointmentInput
) {
  const appointment = await fastify.prisma.appointment.findFirst({
    where: { id, tenantId, deletedAt: null },
  });
  if (!appointment) throw fastify.httpErrors.notFound("Appointment not found");

  if (input.outcome === "raport_complet") {
    // Upload client signature to S3 if provided
    let clientSignatureS3Key: string | null = null;
    const sigData = input.reportData.clientSignature;
    if (sigData?.signatureDataUrl) {
      try {
        clientSignatureS3Key = await uploadClientSignature(tenantId, id, sigData.signatureDataUrl);
      } catch (err) {
        console.error("[finalize] Failed to upload client signature:", err);
      }
    }

    // Save client email if provided
    if (sigData?.clientEmail && appointment.clientId) {
      try {
        await fastify.prisma.client.update({
          where: { id: appointment.clientId },
          data: { email: sigData.clientEmail },
        });
      } catch (err) {
        console.error("[finalize] Failed to update client email:", err);
      }
    }

    // ── Equipment: update existing or create new ──
    let equipmentId = input.equipmentId ?? appointment.equipmentId;
    const eqData = input.equipmentData;

    if (equipmentId && eqData) {
      // Update existing equipment with installation data
      await fastify.prisma.equipment.update({
        where: { id: equipmentId },
        data: {
          ...(eqData.name !== undefined && { name: eqData.name }),
          ...(eqData.internalName !== undefined && { internalName: eqData.internalName }),
          ...(eqData.serial !== undefined && { serial: eqData.serial }),
          ...(eqData.fuel !== undefined && { fuel: eqData.fuel }),
          ...(eqData.deviceType !== undefined && { deviceType: eqData.deviceType }),
          ...(eqData.power !== undefined && { power: eqData.power }),
          ...(eqData.airSupply !== undefined && { airSupply: eqData.airSupply }),
          ...(eqData.feeding !== undefined && { feeding: eqData.feeding }),
          ...(eqData.location !== undefined && { location: eqData.location }),
          ...(eqData.fuelIscir !== undefined && { fuelIscir: eqData.fuelIscir }),
          ...(eqData.deviceAge !== undefined && { deviceAge: eqData.deviceAge }),
        },
      });
    } else if (!equipmentId && appointment.clientId && eqData) {
      // Create new equipment
      const created = await fastify.prisma.equipment.create({
        data: {
          clientId: appointment.clientId,
          type: "CENTRALA",
          name: eqData.name || eqData.deviceType || "Centrală",
          internalName: eqData.internalName || "Centrală",
          serial: eqData.serial,
          fuel: eqData.fuel,
          deviceType: eqData.deviceType,
          power: eqData.power,
          airSupply: eqData.airSupply,
          feeding: eqData.feeding,
          location: eqData.location,
          fuelIscir: eqData.fuelIscir,
          deviceAge: eqData.deviceAge,
        },
      });
      equipmentId = created.id;
    }

    // ── Find existing or create EquipmentRevision ──
    let revisionId = appointment.equipmentRevisionId;
    let revisionHasPdfData = false;

    if (!revisionId && equipmentId) {
      // Look for a recent PENDING revision on this equipment (may have been created by email-ingestion)
      const existingRevision = await fastify.prisma.equipmentRevision.findFirst({
        where: {
          equipmentId,
          createdAt: { gte: new Date(Date.now() - 7 * 24 * 3600_000) },
        },
        orderBy: { createdAt: "desc" },
        select: { id: true, sourceEmailId: true, analysisData: true },
      });

      if (existingRevision) {
        revisionId = existingRevision.id;
        revisionHasPdfData = !!existingRevision.sourceEmailId;
      } else {
        // Create new PENDING revision — wait for email PDF
        const revision = await fastify.prisma.equipmentRevision.create({
          data: {
            equipmentId,
            revisionDate: new Date(),
            status: "PENDING",
            location: eqData?.location ?? null,
          },
        });
        revisionId = revision.id;
      }
    } else if (revisionId) {
      // Re-edit flow — check if revision already has PDF data
      const rev = await fastify.prisma.equipmentRevision.findUnique({
        where: { id: revisionId },
        select: { sourceEmailId: true },
      });
      revisionHasPdfData = !!rev?.sourceEmailId;
    }

    // Replace dataUrl with S3 key in stored data (don't persist huge base64)
    const reportToStore = {
      ...input.reportData,
      clientSignature: sigData
        ? {
            signatureS3Key: clientSignatureS3Key,
            gdprConsent: sigData.gdprConsent,
            gdprConsentAt: sigData.gdprConsentAt,
            clientEmail: sigData.clientEmail,
          }
        : undefined,
    };

    const updated = await fastify.prisma.appointment.update({
      where: { id },
      data: {
        status: "completed",
        completionDataJson: reportToStore as unknown as Prisma.InputJsonValue,
        equipmentId,
        equipmentRevisionId: revisionId,
      },
      include: listInclude,
    });

    // Activate client on revision completion (prospect → active)
    if (appointment.clientId) {
      await fastify.prisma.client.updateMany({
        where: { id: appointment.clientId, status: "PROSPECT" },
        data: { status: "ACTIVE" },
      });
    }

    // Generate ISCIR only when BOTH sources are available (manual report + PDF from email)
    // If PDF hasn't arrived yet, email-ingestion worker will trigger generation when it does
    if (revisionId && revisionHasPdfData) {
      await regenerateIscirDocument(
        fastify, tenantId, id, revisionId,
        sigData?.clientEmail ?? undefined
      );
    }

    // Auto-generate GDPR document if client consented AND doesn't already have one
    if (sigData?.gdprConsent && appointment.clientId) {
      // Log GDPR consent in audit trail
      await fastify.prisma.auditLog.create({
        data: {
          tenantId,
          actorUserId: null,
          entityType: "client",
          entityId: appointment.clientId,
          action: "GDPR_CONSENT",
          metadataJson: {
            appointmentId: id,
            consentAt: sigData.gdprConsentAt,
            clientEmail: sigData.clientEmail,
            signatureS3Key: clientSignatureS3Key,
            hasSignature: !!clientSignatureS3Key,
          },
        },
      });

      const existingGdpr = await fastify.prisma.document.findFirst({
        where: {
          tenantId,
          status: { in: ["COMPLETED", "SIGNED"] },
          template: { categoryCode: "GDPR" },
          clients: { some: { clientId: appointment.clientId } },
        },
      });
      if (!existingGdpr) {
        try {
          await generateAndSendGdpr(fastify, tenantId, appointment.clientId, clientSignatureS3Key);

          // Log GDPR document generation
          await fastify.prisma.auditLog.create({
            data: {
              tenantId,
              entityType: "client",
              entityId: appointment.clientId,
              action: "GDPR_DOCUMENT_GENERATED",
              metadataJson: {
                appointmentId: id,
                clientEmail: sigData.clientEmail,
              },
            },
          });
        } catch (err) {
          console.error("[finalize] Failed to generate GDPR:", err);
        }
      } else {
        console.log(`[finalize] Client ${appointment.clientId} already has GDPR document, skipping.`);
      }
    }

    return updated;
  }

  if (input.outcome === "revenire") {
    await fastify.prisma.task.create({
      data: {
        tenantId,
        title: input.followup.title,
        description: input.followup.description,
        taskType: "followup",
        status: "open",
        priority: input.followup.priority,
        projectId: appointment.projectId,
        clientId: appointment.clientId,
        assignedUserId: input.followup.assignedUserId,
        dueAt: input.followup.dueAt ? new Date(input.followup.dueAt) : undefined,
      },
    });

    return fastify.prisma.appointment.update({
      where: { id },
      data: { status: "completed" },
      include: listInclude,
    });
  }

  // outcome === "programare_noua"
  await fastify.prisma.appointment.create({
    data: {
      tenantId,
      projectId: appointment.projectId,
      clientId: appointment.clientId,
      employeeId: appointment.employeeId,
      type: input.newAppointment.type,
      title: input.newAppointment.title,
      notes: input.newAppointment.notes,
      date: new Date(input.newAppointment.date),
      duration: input.newAppointment.duration,
    },
  });

  return fastify.prisma.appointment.update({
    where: { id },
    data: { status: "completed" },
    include: listInclude,
  });
}

export async function remove(
  fastify: FastifyInstance,
  tenantId: string,
  id: string
) {
  const appointment = await fastify.prisma.appointment.findFirst({
    where: { id, tenantId, deletedAt: null },
  });
  if (!appointment) throw fastify.httpErrors.notFound("Appointment not found");

  // Soft delete
  return fastify.prisma.appointment.update({
    where: { id },
    data: { deletedAt: new Date() },
  });
}

export async function restore(
  fastify: FastifyInstance,
  tenantId: string,
  id: string
) {
  const appointment = await fastify.prisma.appointment.findFirst({
    where: { id, tenantId, deletedAt: { not: null } },
  });
  if (!appointment) throw fastify.httpErrors.notFound("Archived appointment not found");

  return fastify.prisma.appointment.update({
    where: { id },
    data: { deletedAt: null },
    include: listInclude,
  });
}

export async function listArchived(
  fastify: FastifyInstance,
  tenantId: string,
  projectId?: string
) {
  return fastify.prisma.appointment.findMany({
    where: { tenantId, deletedAt: { not: null }, ...(projectId && { projectId }) },
    include: listInclude,
    orderBy: { deletedAt: "desc" },
  });
}
